name: Build customized u-boot

on:
  workflow_dispatch:
    inputs:
      model:
        description: '设备型号'
        required: true
        type: string
        default: 'ZTE_E8820S'
      flash:
        description: 'Flash 类型'
        required: true
        type: choice
        options:
        - 'NAND'
        - 'NAND-NMBM'
        - 'NOR'
        default: 'NAND'
      mtdparts:
        description: 'MTD 分区表'
        required: true
        type: string
        default: '512k(u-boot),512k(u-boot-env),256k(factory),-(firmware)'
      kernel_offset:
        description: 'Kernel Load Address'
        required: true
        type: string
        default: '0x140000'
      gpio_config:
        description: 'GPIO 配置 (格式: reset_pin,sysled_pin)'
        required: true
        type: string
        default: '18,3'
      cpufreq:
        description: 'CPU 频率 (400 - 1200)'
        required: true
        type: number
        default: '880'
      ramfreq:
        description: 'DRAM 频率'
        required: true
        type: choice
        options:
        - '400'
        - '800'
        - '1066'
        - '1200'
        default: '1200'
      ddrparam:
        description: '首选DDR初始化参数'
        required: true
        type: choice
        options:
        - 'DDR2-64MiB'
        - 'DDR2-128MiB'
        - 'DDR2-W9751G6KB-64MiB-1066MHz'
        - 'DDR2-W971GG6KB25-128MiB-800MHz'
        - 'DDR2-W971GG6KB18-128MiB-1066MHz'
        - 'DDR3-128MiB'
        - 'DDR3-256MiB'
        - 'DDR3-512MiB'
        - 'DDR3-128MiB-KGD'
        default: 'DDR3-256MiB'
      oldparam:
        description: '使用旧DDR时序参数'
        required: true
        type: boolean
        default: 'false'
      baudrate:
        description: '波特率'
        required: true
        type: choice
        options:
        - '57600'
        - '115200'
        default: '57600'

jobs:
  build:
    name: Build MT7621 u-boot
    runs-on: ubuntu-22.04
    strategy:
       fail-fast: False

    steps:
      - name: Checkout master directory
        uses: actions/checkout@v4
        with:
          path: uboot-mt7621

      - name: Install essential packages
        run: |
          sudo apt-get update
          sudo apt-get install swig python2-dev
          echo 'switch to python2 as default'
          sudo rm /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python

      - name: Download OpenWrt toolchain
        run: |
          wget -O - https://github.com/DragonBluep/uboot-mt7621/releases/download/20230517/openwrt-toolchain-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz \
            | tar --xz -xf -

      - name: Set old DDR timing parameters
        if:  ${{ inputs.oldparam }}
        working-directory: uboot-mt7621
        run: sed -i 's/0x0C000000/0x0A000000/g' ./arch/mips/mach-mt7621/dramc-legacy/dramc.S

      - name: Compile
        working-directory: uboot-mt7621
        run: |
          # 解析GPIO配置
          IFS=',' read -r reset_pin sysled_pin <<< "${{ inputs.gpio_config }}"
          
          ./customize.sh '${{ inputs.flash }}' '${{ inputs.mtdparts }}' '${{ inputs.kernel_offset }}' \
            "${reset_pin}" "${sysled_pin}" '${{ inputs.cpufreq }}' '${{ inputs.ramfreq }}' \
            '${{ inputs.ddrparam }}' '${{ inputs.baudrate }}'

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.model }}-uboot
          path: "uboot-mt7621/archive/"
      
      - name: Generate timestamp
        id: timestamp
        run: echo "now=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: rename uboot-mt7621
        run: |
          mv uboot-mt7621/archive/u-boot-mt7621.bin uboot-mt7621/archive/${{ inputs.model }}-${{ steps.timestamp.outputs.now }}_u-boot-mt7621.bin
          mv uboot-mt7621/archive/u-boot.img uboot-mt7621/archive/${{ inputs.model }}-${{ steps.timestamp.outputs.now }}_u-boot.img

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ inputs.model }}-${{ steps.timestamp.outputs.now }}
          body: |

            ## 构建参数
            - 设备型号: ${{ inputs.model }}
            - 闪存类型: ${{ inputs.flash }}
            - 分区表: ${{ inputs.mtdparts }}
            - 内核加载地址: ${{ inputs.kernel_offset }}
            - 复位按钮GPIO: ${{ inputs.reset_pin }}
            - 系统LED GPIO: ${{ inputs.sysled_pin }}
            - CPU频率: ${{ inputs.cpufreq }} MHz
            - 内存频率: ${{ inputs.ramfreq }} MHz
            - DDR初始化参数: ${{ inputs.ddrparam }}
            - 使用旧DDR参数: ${{ inputs.oldparam }}
            - 波特率: ${{ inputs.baudrate }}
          files: uboot-mt7621/archive/*
          tag_name: ${{ inputs.model }}-${{ steps.timestamp.outputs.now }}
